Repository oliverj96/katy_trail_app, pull requests merged in 2020-04, with the labels that each got.

#49 Johnsono locations
  lib/home_page/explore.dart
  lib/home_page/homepage.dart
  lib/home_page/map.dart
  lib/location_page/ExplorePage.dart
  lib/location_page/LocationPage.dart
  lib/location_page/location_list_cards.dart
  lib/main.dart
  lib/map_page/location-card.dart
  lib/map_page/maps.dart
Labels: enhancement

#55 annag-fixlocationcards
  lib/map_page/location-card.dart
Labels: enhancement

#56 Annag pushnotifications
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/drawable/location.png
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Runner/Info.plist
  lib/main.dart
  lib/map_page/maps.dart
  pubspec.yaml
Labels: enhancement

#79 Annag notificationicon
  android/app/src/main/res/drawable/app_icon.png
  android/app/src/main/res/drawable/location.png
  lib/main.dart
  lib/map_page/maps.dart
Labels: Low priority, enhancement

#81 added bookmarks icon to maps page
  lib/map_page/maps.dart
Labels: enhancement

#84 finalized about page, added images
  lib/about_page/AboutImage.dart
  lib/about_page/AboutPage.dart
  lib/about_page/TextSection.dart
  lib/about_page/TitleSection.dart
  pubspec.yaml
Labels: enhancement

#85 cleaned up class names and fixed some location class issues
  lib/about_page/about_image.dart
  lib/about_page/about_page.dart
  lib/about_page/text_section.dart
  lib/about_page/title_section.dart
  lib/bookmark_page/bm_cards.dart
  lib/home_page/about.dart
  lib/home_page/explore.dart
  lib/home_page/home_page.dart
  lib/location.dart
  lib/location_page/explore_page.dart
  lib/location_page/location_list_cards.dart
  lib/location_page/location_page.dart
  lib/main.dart
  lib/map_page/location-card.dart
Labels: Low priority

#87 Johnsono explore format
  assets/images/noimage.png
  lib/location.dart
  lib/location_page/explore_page.dart
  lib/push_handler.dart
  pubspec.yaml
Labels: enhancement

#91 Annag addicontoaboutpg
  lib/about_page/about_page.dart
  lib/home_page/about.dart
  lib/home_page/home_page.dart
  lib/location.dart
Labels: enhancement
